version: "3.8"

services:

  vector_db:
    image: elasticsearch:8.10.1
    networks:
      - semantic
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}

  app:
    container_name: rag_app
    networks:
      - semantic
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - vector_db
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1 --reload"


networks:
  semantic:
    driver: bridge