from typing import List

from pydantic import BaseModel, Field


class ResponseSchema(BaseModel):
    """
    Schema for the LLM response
    """

    success: bool = Field(
        description="Whether llm could generate a response from context"
    )
    response: str = Field(
        default=None,
        description="Response generated by llm. If could not be generated, "
        "response should be `Could not generate response`",
    )
    context: List[str] = Field(default=None)
    file_loc: List[str] = Field(default=None)
